apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: cn-demo
  name: cn-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cn-demo
  template:
    metadata:
      labels:
        run: cn-demo
    spec:
      containers:
      - image: javaplus/cloud-native-demo:1
        imagePullPolicy: IfNotPresent
        name: cn-demo
        env:
          - name: USER_DEFINED_1   
            valueFrom:   
              configMapKeyRef:
                  # The ConfigMap containing the value you want to assign to USER_DEFINED_1   
                name: app-config   
                # Specify the key associated with the value   
                key: cm.user_defined_1
          - name: USER_DEFINED_2 
            valueFrom:   
              configMapKeyRef:
                name: app-config   
                key: cm.user_defined_2
          - name: USER_DEFINED_3 
            valueFrom:   
              configMapKeyRef:
                name: app-config   
                key: cm.user_defined_3
        envFrom:
        - configMapRef:
            name: redis-env
        command:
          - sh
          - -c
          - |
            python app.py --redis-host $(REDIS_HOST) 
        resources:
          limits:
            cpu: 1
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        
      restartPolicy: Always
      terminationGracePeriodSeconds: 2
